service:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: mgmt
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: kibana
    port: 5601
    protocol: TCP
    targetPort: 5601
  - name: keycloak
    port: 20000
    targetPort: 20000
    protocol: TCP
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: jaeger
    port: 16686
    targetPort: 16686
    protocol: TCP
  - name: kiali
    port: 20001
    targetPort: 20001
    protocol: TCP
  - name: mssql
    port: 1433
    targetPort: 1433
    protocol: TCP