apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: acr-helmrepo
  namespace: default
spec:
  interval: 1m
  url: https://codetalksacr.azurecr.io/helm/v1/repo
  secretRef:
    name: helm-auth

