apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-vsvc
spec:
  hosts:
  - "*"
  gateways:
  - "apigateway"
  http:
    - name: keycloak
      headers:
        request:
          set:
            "X-Forwarded-Port": "20000"
      match:
      - port: 20000
      route:
      - destination:
          host: keycloak.default.svc.cluster.local
          port:
            number: 80