apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vsvc
spec:
  hosts:
  - "*"
  gateways:
  - "apigateway"
  http:
    - name: kiali
      match:
      - port: 20001
      route:
      - destination:
          host: kiali.istio-system.svc.cluster.local
          port:
            number: 20001