apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mssql-vsvc
spec:
  hosts:
  - "*"
  gateways:
  - apigateway
  tcp:
    - match:
      - port: 1433
      route:
      - destination:
          host: mssql
          port:
            number: 1433